### ISSUE TITLE
Unable to use chromedriver_autodownload

### ISSUE THREAD

**Issue by LukaszSiudakiewicz** [appium/appium-chromedriver#157]
Starting appium with --allow-insecure=chromedriver_autodownload flag
Creating new session with chromedriverChromeMappingFile and chromedriverExecutableDir capabilitites 

**Expected result:**
Proper chromedriver should be downloaded into the chromedriverExecutableDir and chromedriverChromeMappingFile should be updated

**Actual result:**
Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '73.0.3683'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature

**Environment**
Appium 1.16.0
Ubuntu 18.04

**Appium logs:**
[appium.log](https://github.com/appium/appium-chromedriver/files/4086834/appium.log)

**Comment by mykola-mokhnach** [comment]
I don't observe the `chromedriver_autodownload` is enabled in the attached log

**Comment by LukaszSiudakiewicz** [comment]
Is this part is not showing enable insecure server flags?

    "...
    2020-01-20 14:47:36:230 - [Appium]   allowInsecure: {
    2020-01-20 14:47:36:230 - [Appium]     0: chromedriver_autodownload
    2020-01-20 14:47:36:231 - [Appium]     1: adb_shell
    2020-01-20 14:47:36:231 - [Appium]   }.."

**Comment by mykola-mokhnach** [comment]
True, it is enabled. Most likely the server does not have a possibility to connect to the chromedrivers storage at: https://chromedriver.storage.googleapis.com

So this is where the timeout exception is coming from
```
2020-01-20 14:48:01:029 - [Chromedriver] RequestError: Error: ETIMEDOUT
2020-01-20 14:48:01:030 - [Chromedriver]     at new RequestError (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/request-promise-core/lib/errors.js:14:15)
2020-01-20 14:48:01:030 - [Chromedriver]     at Request.plumbing.callback (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/request-promise-core/lib/plumbing.js:87:29)
2020-01-20 14:48:01:030 - [Chromedriver]     at Request.RP$callback [as _callback] (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/request-promise-core/lib/plumbing.js:46:31)
2020-01-20 14:48:01:031 - [Chromedriver]     at self.callback (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/request/request.js:185:22)
2020-01-20 14:48:01:031 - [Chromedriver]     at Request.emit (events.js:198:13)
2020-01-20 14:48:01:032 - [Chromedriver]     at Timeout._onTimeout (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/request/request.js:852:16)
2020-01-20 14:48:01:032 - [Chromedriver]     at ontimeout (timers.js:436:11)
2020-01-20 14:48:01:032 - [Chromedriver]     at tryOnTimeout (timers.js:300:5)
2020-01-20 14:48:01:033 - [Chromedriver]     at listOnTimeout (timers.js:263:5)
2020-01-20 14:48:01:033 - [Chromedriver]     at Timer.processTimers (timers.js:223:10)
```

**Comment by LukaszSiudakiewicz** [comment]
Thank You it looks like this is the case.

**Comment by aakashr23** [comment]
Hi,

I'm facing a similar issue, but its not due to connection issues.

Started Appium server using the command mentioned in docs, log as follows:
appium --allow-insecure chromedriver_autodownload
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]     0: chromedriver_autodownload
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723



Capabilities which I've used in code: 
capabilities.setCapability("chromedriverChromeMappingFile", "@PathToFile");
capabilities.setCapability("chromedriverExecutableDir", "D:\Mobile_Android\");

Error log:
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1612277418201 (20:20:18 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: No Chromedrivers found in 'D:\Mobile_Android\'
[debug] [W3C]     at Object.wrappedLogger.errorAndThrow (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:79:13)
[debug] [W3C]     at Chromedriver.errorAndThrow [as start] (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:540:11)
[debug] [W3C]     at AndroidUiautomator2Driver.setupNewChromedriver (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\context.js:429:3)
[debug] [W3C]     at AndroidUiautomator2Driver.startChromeSession (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\context.js:245:23)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:353:7)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:211:7)
[debug] [W3C]     at AppiumDriver.createSession (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\lib\appium.js:353:35)
[debug] [W3C]     at AppiumDriver.executeCommand (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:376:13)
[debug] [W3C]     at AppiumDriver.executeCommand (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\lib\appium.js:482:14)
[debug] [W3C]     at asyncHandler (C:\Users\aakash.r\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:306:21)



Its searching for existing drivers instead of downloading I guess.
Please let me know how to fix this if there is an issue on my side.

**Comment by KazuCocoa** [comment]
Please try out the latest Appium version with `chromedriver_autodownload` in http://appium.io/docs/en/writing-running-appium/security/#insecure-features

**Comment by aakashr23** [comment]
Thank you @KazuCocoa. Upgrading appium worked for me.
I tried with 1.15.1 as it is mentioned in appium docs that this feature is supported from 1.8.0 onwards. Please consider updating the version number in docs. Thank you for your help.
