### ISSUE TITLE
Error trying to install Chromedriver binary. Waiting and trying again.

### ISSUE THREAD

**Issue by tomtom87** [appium/appium-chromedriver#26]
I cannot install the appium-chromedriver from npm currently as I get the following error:

```
Error trying to install Chromedriver binary. Waiting and trying again.
Error: Cannot find module './build/lib/install'
```

What can I do to fix this?

**Comment by beeva-pedrocuello** [comment]
I need support fopr the same.

**Comment by imurchie** [comment]
This should be fixed in the latest version of `appium-chromedriver`.

**Comment by beeva-pedrocuello** [comment]
Hi,

I have solved this very easy, the trouble is not the version of chromedriver or appium the proble is you don't have to install npm by "sudo" because appium won't work...

I copy the solution that i found from a comment of the user: "deepak" solution worked very well for me:

http://stackoverflow.com/questions/22374416/how-to-setup-appium-in-ubuntu-for-android

Do not install nodejs through apt-get, which will need sudo rights and appium will not work if node is installed as sudo user. If you have already installed remove it using

sudo apt-get remove nodejs
sudo apt-get remove npm
Download latest nodejs linux binaries form http://nodejs.org/download/

Extract into a folder that doesn't need sudo rights to access, for example your home folder.

tar -xvf <downloaded_binary_tar.gz>
Add the following line to your ~/.bashrc file.

export PATH=$PATH:<full_path_of_the_extracted_node_folder>/bin
Open a now terminal and do

npm install -g appium
appium

Best regards,

**Comment by tomtom87** [comment]
:+1:  yes sorry guys I forgot this ticket, I fixed this also by using a root installation. Please try what @beeva-pedrocuello  suggests and start appium as so

```
$ npm install -g appium
$ appium &
$ mocha tests.js
```
