### ISSUE TITLE
startSession() should have restartAdb logic as present in previous versions of appium

### ISSUE THREAD

**Issue by rkavalap** [appium/appium-chromedriver#37]
@jlipps @imurchie  got any thoughts on this. 
line 168
async startSession does not handle failed to run adb command scenario. restartAdb logic is required. 
This would require appium-chromedriver to take dependency on appium-adb. 

below snipped pulled from appium v1.3.5 chromedriver.js - proxyNewSession method
if (typeof body !== "undefined" &&
                 typeof body.value !== "undefined" &&
                 typeof body.value.message !== "undefined" &&
                 body.value.message.indexOf("Failed to run adb command") !== -1) {
        logger.error("Chromedriver had trouble running adb");
        if (!alreadyRestarted) {
          logger.error("Restarting adb for chromedriver");
          return this.adb.restartAdb(function () {
            this.adb.getConnectedDevices(function () {
              doProxy(true);
            }.bind(this));
          }.bind(this));
        } else {
          cb(new Error("Chromedriver wasn't able to use adb. Is the server up?"));
        }
      } else {
        logger.error("Chromedriver create session did not work. Status was " +
                     res.statusCode + " and body was " +
                     JSON.stringify(body));
        cb(new Error("Did not get session redirect from Chromedriver"));
      }

**Comment by imurchie** [comment]
Seems like something we should do. Though I think we need to pass in the `adb` object, rather than use one of our own, so that it can be configured in the right way without duplicating all the logic.

Perhaps in `appium-android-driver` when we instantiate the ChromeDriver object we could pass in the `adb` instance.

https://github.com/appium/appium-android-driver/blob/master/lib/commands/context.js#L194
